<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://pack_drop_dept/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://pack_drop_dept/" name="drop_departmentService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://pack_drop_dept/" schemaLocation="http://automation:8080/dropDepartmentWS/drop_departmentService/__container$publishing$subctx/WEB-INF/wsdl/DropDepartmentService_schema1.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </xsd:schema>
  </types>
  <message name="drop_down_deptWS">
    <part name="parameters" element="tns:drop_down_deptWS"/>
  </message>
  <message name="drop_down_deptWSResponse">
    <part name="parameters" element="tns:drop_down_deptWSResponse"/>
  </message>
  <portType name="drop_department">
    <operation name="drop_down_deptWS">
      <input message="tns:drop_down_deptWS"/>
      <output message="tns:drop_down_deptWSResponse"/>
    </operation>
  </portType>
  <binding name="drop_departmentPortBinding" type="tns:drop_department">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="drop_down_deptWS">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="drop_departmentService">
    <port name="drop_departmentPort" binding="tns:drop_departmentPortBinding">
      <soap:address location="http://automation:8080/dropDepartmentWS/drop_departmentService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </port>
  </service>
</definitions>